pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'udaykishoreresu/emp-login-service'
        DOCKER_CREDENTIALS = credentials('bd5fafc2-aa2b-4bed-bc95-ee64f7cbb057')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh '''
                    docker run --rm -v "$PWD":/app -w /app golang:1.21.5 /bin/bash -c "
                    go version
                    cd emp-login-service
                    go mod download
                    go build -o main ./cmd/main.go
                '''
            }
        }

        stage('Test') {
            steps {
                script {
                    docker.image('golang:1.21.5').inside {
                        dir('emp-login-service') {
                            sh 'go test ./... -v'
                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('emp-login-service') {
                    script {
                        docker.build("${DOCKER_IMAGE}:${BUILD_NUMBER}")
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS) {
                        docker.image("${DOCKER_IMAGE}:${BUILD_NUMBER}").push()
                        docker.image("${DOCKER_IMAGE}:${BUILD_NUMBER}").push("latest")
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
