pipeline {
    agent any

    environment {
        DOCKER_PATH = '/usr/local/bin/docker'
        PATH = "${env.DOCKER_PATH}:${env.PATH}"
        DOCKER_IMAGE = 'udaykishoreresu/emp-login-service'
        DOCKER_CREDENTIALS = credentials('bd5fafc2-aa2b-4bed-bc95-ee64f7cbb057')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh """
                    ${DOCKER_PATH} run --rm -v "\${WORKSPACE}":/app -w /app golang:1.21.5 /bin/bash -c '
                    go version
                    cd Projects/emp_timesheet_app/emp-login-service
                    go mod download
                    go build -o main ./cmd/main.go
                '
                """
            }
        }

        stage('Test') {
            steps {
                script {
                    def image = docker.image('golang:1.21.5')
                    image.inside {
                        sh """
                            cd Projects/emp_timesheet_app/emp-login-service
                            go test ./... -v
                        """
                        }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('emp-login-service') {
                    script {
                        docker.build("${DOCKER_IMAGE}:${BUILD_NUMBER}")
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS) {
                        docker.image("${DOCKER_IMAGE}:${BUILD_NUMBER}").push()
                        docker.image("${DOCKER_IMAGE}:${BUILD_NUMBER}").push("latest")
                    }
                }
            }
        }

        stage('Docker Check') {
            steps {
                sh '${DOCKER_PATH} --version'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
